baseURL = ""
languageCode = "en-us"
title = "Shelly Sachdev"
theme = "personal-web"
copyright="Â© Shelly Sachdev"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Shelly :wave:"
  sub = "I'm a Computer Science Teacher and a freelance Tech. Writer"

[params.main]
  latestPublishHeader = ""

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.jpg" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = '/images/profile.jpg'

[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  linkedin = "https://www.linkedin.com/in/shellysachdev23"
  facebook = "https://www.facebook.com/shelly.sachdev"
  youtube = "https://www.youtube.com/@shellysachdev/videos"
  
  
[params.contact]
  email = "sachdev.shelly@gmail.com"
  text= "Say Hello" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/post/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true